language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
  - secure: FFIdBO87dpEYWFbutUFwmdE1ANYVpafAf/Ii3fB6O4nHqWgRLqTAU9KF6T+qVyUPE75PMjHXXPjffPCslSSiNAEzOAPShNlyHXTIpNUOIwfBzlmy7ZUX+g6oPeI7fwEGWu4CON0XRrg0tCtY17KvVKJs2QpyUm+4r7vn6N9IQcOMT0p+sPtVJyOUtuICRxG8xMnnpCzMZkeq3qvTzaB0PPOhzRMo335HBI+4shwvp2PdeZDqE2CZXe+yeXycdh5rEyeYhOndm67PWvatzqJtiBUIcjlt2/SolF3S1hXBHAD8dnFYtWjpKn3zuTW+PzW+Lvcbnl+BYDyTZ5zZ01vKjzeE25+pN6+xWPeq7zb7R3jXEoDekr/BKV4sU+0N3R7T2ZQwVcc6qz8c7T2aK7S8kom5m6Xn7UMJROGs6DuuYUQMYBQ9gtzkBN79weK5dBgG7tIfTpVzAdRKrcYtmzakImAmSqU81/veH04jp5/BVWaUo+3o4ftwyZaz0Ze2sY8w3ZWs32HPjPF9gEZ/L+1Lwf4kLh8fQ1CHjXV6j0HZFPloPt+m36qMW9DAi1BSXZCcQeQGuatJzAEEUNirLWtaEm5jVjckdICOE3RngGFaVpGMrOcbsVJLXkX71jX8peOUy4mNloLSQm3n79Afyp0VcNXMk9J94m08oU6uik8jM80=
